name: Hussein Auto-Build APK

on:
  push:
    branches: [ "main" ] # يشتغل تلقائياً أول ما ترفع الكود

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4 # حدثناه للإصدار الرابع

    - name: set up JDK 17
      uses: actions/setup-java@v4 # حدثناه للإصدار الرابع
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4 # هذا هو حل المشكلة اللي بالصورة ✅
      with:
        name: Hussein-GoldAI-Trader
        path: app/build/outputs/apk/debug/app-debug.apk
